n1=float(input("enter first number"))
n2=float(input("enter second number"))
Sum=(n1+n2)
print(Sum)
SUBTRACT=(n1+n2)
print(SUBTRACT)
MULTIPLY=(n1*n2)
print(MULTIPLY)
DIVIDE=(n1/n2)
print(DIVIDE)
MODULUS=(n1%n2)
print(MODULUS)
